apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: rabbitmq-binding-retry
  namespace: default
spec:
  policies:
    retries:
      no-retry:
        policy: constant
        backoffDuration: "0s"
        maxRetries: 0
      limited-retry:
        policy: exponential
        backoffDuration: "200ms"
        maxRetries: 3
  targets:
    components:
      - name: news_request_queue
        retries: no-retry
