---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    AppUser:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Anton
        email:
          type: string
          example: aplaksin2000@gmail.com
        preferences:
          type: string
          example: I like reading news about eroupean politics and science
paths:
  "/app_users":
    get:
      summary: Retrieves a list of app users
      responses:
        '200':
          description: Current app users
    post:
      summary: Creates a new app user
      parameters: []
      responses:
        '201':
          description: App user created
      requestBody:
        content:
          application/x-www-form-urlencoded;charset=UTF-8:
            schema:
              type: string
        required: true
        description: CSRF token
  "/app_users/{id}":
    get:
      summary: Retrieves a specific app user
      responses:
        '200':
          description: App user found
        '404':
          description: App user not found
    put:
      summary: Updates a specific app user
      responses:
        '200':
          description: App user updated
    delete:
      summary: Deletes a specific app user
      responses:
        '204':
          description: App user deleted
        '404':
          description: App user not found
servers:
- url: http://127.0.0.1:8081
